java_test(
    name = "RestClientTest",
    srcs = ["RestClientTest.java"],
    deps = [
        "//:autovalue",
        "//:autovalue_gson",
        "//src/main/java/com/github/pselamy/tiingo/api/rest:rest_client",
        "//src/main/java/com/github/pselamy/tiingo/api/rest:rest_client_module",
        "//src/main/java/com/github/pselamy/tiingo/api/testing:fake_http_request_transport",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_http_client_google_http_client",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_truth",
        "@maven//:com_ryanharter_auto_value_auto_value_gson_factory",
    ],
)
