java_test(
    name = "rest_client_test",
    srcs = ["RestClientTest.java"],
    deps = [
        "//src/main/java/com/github/pselamy/tiingo/api/rest:rest_client",
        "@autovalue_bazel//:autovalue",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        #        "@maven//:com_ryanharter_auto_value_auto_value_gson",
        #        "@maven//:com_ryanharter_auto_value_auto_value_gson_annotations",
        #        "@maven//:com_ryanharter_auto_value_auto_value_gson_factory",
    ],
)
