package(default_visibility = [
    "//src/main/java/com/github/pselamy/tiingo:__subpackages__",
    "//src/test/java/com/github/pselamy/tiingo:__subpackages__",
])

java_library(
    name = "api_key",
    srcs = ["ApiKey.java"],
    deps = [
        "//:autovalue",
    ],
)

java_library(
    name = "asset_type",
    srcs = ["AssetType.java"],
    deps = [],
)

java_library(
    name = "candle",
    srcs = ["Candle.java"],
    deps = [
        "//:autovalue",
    ],
)
