java_library(
    name = "tiingo_client",
    srcs = ["TiingoClient.java"],
    deps = [
        "//src/main/java/com/github/pselamy/tiingo/api/models:api_key",
        "//src/main/java/com/github/pselamy/tiingo/api/models:asset_type",
        "//src/main/java/com/github/pselamy/tiingo/api/services:candle_service",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
    ],
)
