name: Format Java Code

on:
  push:
    branches:
      - main
    paths:
      - '**.java'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
